### ISSUE TITLE
[QUESTION] How to make factoid-submit call to daemon?

### ISSUE THREAD

**Issue by MitchellBerry** [FactomProject/factomd#29]
Understand wallet is preferable.
Version, 6 byte timestamp, RCD1/signatures is easy enough.
The remainder is just inputs/outputs/amounts? Any simple way to get these hashes? and are the checksums/magic numbers removed first? 
A get-transactions call lists nearly everything needed besides these.

Use a python wrapper for the api and requests auto-escapes the inline json of submit, so far it's messy to fix, curl or cli for the same transaction works. Considering submit through daemon instead, possibly easier, well in my case at least.

Also, factoid-sub-fee is missing from the api docs? 

Cheers!

**Comment by carryforward** [comment]
Well, here are a few points.  

1. we never really expected people to be building their own factoid transactions.  it isn't really hard, and is documented to the binary level, so is doable.  we figured most people would just top up their entry credit balances then let the programs run from there.  
https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#factoid-transaction
The signatures cover the Header, Inputs, Outputs, and EC Purchases. The RCD is not part of the signature hash.  We will also be updating the validity time to +- 1 hour instead of 24 hours from the timestamp.  This lowers the memory overhead, among other things.

The TXID is the SHA256 hash of same data being signed.  Sadly it looks like SHA512 is used as the digest internal to ed25519 though.  http://crypto.stackexchange.com/questions/3596/is-it-possible-to-pick-your-ed25519-public-key

Building the entries and making a commit for those is pretty straightforward:
https://github.com/FactomProject/Testing/blob/master/examples/python/writeFactomEntryAPI.py
https://github.com/FactomProject/Testing/blob/master/examples/python/writeFactomChainAPI.py
It may be as straightforward for factoid transactions too.

2. Along with m2, we are releasing both a new API wallet, as well as a v2 API.  the v2api is json based.

The v1 API is still supported in the M2 code though.  The V2 API is still a little in flux until we launch, so there isn't much public on it yet.

The current API wallet (fctwallet) will still be supported, and will still work, but it will not get the advantages of the quick response times.

the new wallet (factom-walletd) uses a json style interface to it.  it also has passwords and TLS, which fctwallet does not.  It is also BIP44 based, so the backups are portable.


Do you want to handle the private keys, or do you want the wallet to?  Factom-walletd I suppose can be used now to build the transactions, then use the compose call to export the fully formed+signed transaction.  Then you can use the current factomd http://localhost:8088/v1/factoid-submit/ call to get it into the system.  Let me know if you are interested in this approach, and I can get you some preliminary docs.
