### ISSUE TITLE
Simulator Setup on Linux

### ISSUE THREAD

**Issue by MitchellBerry** [FactomProject/factomd#30]
Minor thing starting from scratch on lubuntu, but someone else might find it useful. 
compiling shows 2 repos missing, had to download manually. Also needed to change permissions for /.factom folder to initialise databases, which didn't occur with v1

> Compiling:  factomd
> ../factom/addresses.go:16:2: cannot find package "github.com/FactomProject/go-bip44" in any of:
>     /usr/local/go/src/github.com/FactomProject/go-bip44 (from $GOROOT)
>     /home/m/src/github.com/FactomProject/go-bip44 (from $GOPATH)
> ../factom/resolve.go:10:2: cannot find package "github.com/FactomProject/netki-go-partner-client" in any of:
>     /usr/local/go/src/github.com/FactomProject/netki-go-partner-client (from $GOROOT)
>     /home/m/src/github.com/FactomProject/netki-go-partner-client (from $GOPATH)

Fixed with:
go get github.com/FactomProject/go-bip44
go get github.com/FactomProject/netki-go-partner-client

And when using Map, nodes have a mkdir error complaining its not a folder. Saves as a blank file instead, this is Map overwriting?

> Could not create /home/m/.factom/m2/database/Log/Sim1
>  error: mkdir /home/m/.factom/m2/database/Log/Sim1: not a directory

**Comment by carryforward** [comment]
Thanks for the report.  

The map database we haven't really been testing with locally for a while.  we are mostly using the ldb database, as that is what will be used in production.  What happens when you specify -db=LDB on the command line when launching?  The latest defaults will use LBD.

Go get has some limitations which need to be worked around.  the bip44 thing you found is part of that deficiency.

Now that I know you would like to test it, I will promote our latest greatest to the master & m2 branches.  The code you have been testing is several months old.

**Comment by MitchellBerry** [comment]
Yeah same error with using ldb setting, it's just in Log though, ldb/SimX folders are still created
So in /Log :  journals have content, SimX are just empty files, node logs empty even on debug though

Any particular net setting that should be used?

**Comment by carryforward** [comment]
This covers M1 which has been deprecated for a few months now.
