### ISSUE TITLE
Show hostname on console and control panel

### ISSUE THREAD

**Issue by stackdump** [FactomProject/factomd#608]
From Discord: 

[Bedrock] jcheroskeToday at 12:57 PM
Not sure if this is the right place to ask this, but I was wondering if the 8090 console could have the hostname added to the display? All my nodes look alike!
...
[Bedrock] jcheroskeToday at 1:33 PM
It's obviously not a big deal, but it's a feature I'd like to see in the console. That way, no matter how you connect to your node, you'll see the name that the node itself is called. Seems useful

**Comment by sambarnes** [comment]
The enterprise wallet does the same thing, and this is it's explanation:
> This compiles our HTML, CSS, JS, and images into golang .go files. That way we don't need to worry about pathing while serving files as everything is compiled into the binary.

To compile the modified templates and js for the control panel, there's some instructions here:
https://github.com/FactomProject/factomd/blob/master/controlPanel/README.md

This section of the codebase is mostly from Steven I  believe. I'm not all that familiar with it yet, I just know the basic gist of it from when I was looking at enterprise-wallet stuff

**Comment by stackdump** [comment]
FYI currently would be OK to branch from Master to work on this - when you are ready someone can create an FD-XXX branch for you to merge into

**Comment by Emyrk** [comment]
@PaulBernier 
The compile script is here: https://github.com/FactomProject/factomd/blob/master/controlPanel/compile.sh
This is the dependency for building: https://github.com/FactomProject/staticfiles

I need to update the readme, but we decided to not minify things, as the extra build step wasn't buying us much, as most of the files are served over localhost. We can move back to a minified build as the control panels are being used more remotely, but for now the 'uncompressed' part of that readme is out of date.

**Comment by PaulBernier** [comment]
Ok I managed to make the code change to display the info in the control panel this way:

![screenshot from 2018-11-17 11-26-25](https://user-images.githubusercontent.com/5141652/48653795-c1413600-ea5b-11e8-9cdc-66b13774ef80.png)

I asked jcheroske and operators and Discord and it was fine.
The title mentions display in console too, what place is this referring to exactly?

Now that works fine if factond is running directly on the OS... but I experimented with the docker container and the hostname of a docker container is the container id (not the hostname of the host OS)... Maybe there is an option to force the hostname of the container, would need to be investigated.

**Comment by PaulBernier** [comment]
For Docker container, seems it is as easy as adding a `--hostname` parameter when launching the container (https://www.digitalocean.com/community/tutorials/naming-docker-containers-3-tips-for-beginners), so all good!

**Comment by jcheroske** [comment]
Yes, being able to set the name manually via a startup parameter or via a
conf file setting will work just as well. I can do the hostname lookup in
ansible and then pass it in.

Jay

**Comment by PaulBernier** [comment]
@stackdump so if someone can create a branch I could push to show you my little change to the control panel.

**Comment by jcheroske** [comment]
Brian, you're reading my mind. I was going to suggest it be just a human
readable name that the admin can set to whatever they need. Goodbye "Your
Node"

**Comment by PaulBernier** [comment]
Ok if I sum up the requirements so far:

- [ ] introduce a new variable nodename that can be set via a factomd flag `nodename`. If that flag is not set, fallback to the hostname of the machine?
- [ ] Display the nodename value in place of "YOUR NODE" in the control panel
- [ ] Display the nodename in the console when factomd boot

**Comment by carryforward** [comment]
These both sound good:
`Display the nodename value in place of "YOUR NODE" in the control panel`
`Display the nodename in the console when factomd boot`

This sounds desirable, yes:
`introduce a new variable nodename that can be set via a factomd flag nodename. `

This one I am not so sure of.  we can get the same effect by using bash/environment variables.  making it a default might get complex with different operating systems.  There is only a limited amount of space, so I don't know if it will mess things up with unusually named machines.  We could compensate by truncating, but that gets into more complex management that might be beyond the scope of this update.
`If that flag is not set, fallback to the hostname of the machine?`
I would be happy with simply specifying the node name instead of trying to deal with host names.  Is the host name by default something that should be in there @PaulBernier?

**Comment by jcheroske** [comment]
1) You could always display the hostname in smaller text to the right, like in the image above. If the `-nodename` flag is not present, you could just default back to 'YOUR NODE'
2) Yes
3) Yes

So, for example, if no `-nodename flag was passed, it would read:
```
YOUR NODE v6.0.1@hostname.com
```
If you pass in `-nodename`, then you get:
```
NODENAME v6.0.1@hostname.com
```

**Comment by carryforward** [comment]
From my perspective at least from the portainer viewpoint, hostname is not terribly useful.  On AWS it looks like `ip-172-99-6-70`.  I'm hearing on docker it would require special flags to make work.  On some VM systems it would show the name of the VM, but that is kind of specialized.

I was trying to stay away from combining the version field with other things, since this can be set to arbitrary values already: 
https://github.com/FactomProject/factomd/commit/169813760948eea4fe4c4eee803b4c87d39f09a7

How valuable is having both hostname and a nodename?

**Comment by PaulBernier** [comment]
So after looking a bit at the code I noticed that the `State` object has an attribute `FactomNodeName` (Usually FNode0). I'm assuming I should *not* try to re use that variable right? Because I see it's already used in many places that seem non trivial.

**Comment by stackdump** [comment]
Yea it think mostly it would affect simulation where there would be several nodes running in the same go processes - but I agree it's safer not to use that.

**Comment by PaulBernier** [comment]
https://github.com/FactomProject/factomd/pull/620

**Comment by carryforward** [comment]
yah, definitely don't use that name Fnode0.  There are tons of very weird dependencies on that name.

**Comment by carryforward** [comment]
This has been passed onto testing.  the code review looks good.

**Comment by carryforward** [comment]
merged into master.  Thank you paul!
