### ISSUE TITLE
Ineffectual assign inside deferred function

### ISSUE THREAD

**Issue by AdamSLevy** [FactomProject/factomd#624]
https://github.com/FactomProject/factomd/blob/ddc48171d2ea20c4d93dfb69ec8464f021a259c9/common/entryBlock/entry.go#L255-L261

The `var err error` declared on line 256 is not properly returned by the function in the event of a panic. Inside the deferred recover function `err` is set, but this will be out of scope when the function returns. 

This example demonstrates this issue: https://play.golang.org/p/KZ_3-ynuguN
You can see that `go vet` catches this issue in the above example, but only because `err` is never used in the function body, so this is an easy thing to have slip by.

This can easily be fixed by removing `var err error` and using named return values in the function declaration:
```
func (e *Entry) UnmarshalBinaryData(data []byte) (data []byte, err error) {
```

**Comment by carryforward** [comment]
good find @AdamSLevy.  I would love a pull request for this.  Since the last time you raised some issues we now have a good process for taking contributions.

I have made a ticket in the ticketing system to help track it on it's way to release and a way to give it a tracking number.  (The active tickets will be published, but it is basically a pointer to what you wrote here).

1. Can you add your name to this branch with a pull request from your GH account?
https://github.com/FactomProject/factomd/tree/adam_cla

2. Once that exists, can you submit a pull request to this branch:
https://github.com/FactomProject/factomd/tree/FD-772_error_string_scope



Thank you again for pointing this out and in advance for fixing it.

**Comment by AdamSLevy** [comment]
It appears this was resolved but not closed.
