### ISSUE TITLE
Unsupported compiler version error on Mac 

### ISSUE THREAD

**Issue by kirit93** [FactomProject/factomd#639]
I followed the instructions here - https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md 
to download and install Factom on my Mac.

When I run the factomd binary from $GOPATH/bin I get the following error - 
```//////////////////////// Copyright 2017 Factom Foundation
//////////////////////// Use of this source code is governed by the MIT
//////////////////////// license that can be found in the LICENSE file.
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
```

How do I fix this? Which compiler is not the right version?

**Comment by kirit93** [comment]
Thank you, Brian! I changed the 1.6 to 1.11 and it worked perfectly.

Just curious, how come this repo has 1.6 instead of 1.11?

**Comment by carryforward** [comment]
it has 1.6 through 1.10.  that was a safe line to change since you probably weren't running such an old version.  The next version of factomd will work just fine without editing.

It looks like the next version of golang 1.12 is getting released soon too.  https://github.com/golang/go/milestone/65  This shows how long this latest release has taken.

**Comment by carryforward** [comment]
This should be fixed now.  golang 1.12 (the latest go version) is now supported in the master branch.
