### ISSUE TITLE
FD-869 Determine if factomd out of ignore or not in API `diagnostics` call

### ISSUE THREAD

**Issue by ilzheev** [FactomProject/factomd#664]
For correctly managing nodes in Open Node Pool we need to determine (via factomd API) if node is in ignore or not.

**Possible problems when node is in ignore:**
1) Commit entry/chain may stuck it (See FD-862, but this unexpected behaviour will be fixed soon)
2) Possible outdated data while get blockchain info via node in ignore
3) Time lag to process new entries/chains (entries/chains processed only after node goes out of ignore, so it may be 1-2 blocks lag, depending on --startdelay factomd flag)

This problems are important for any projects / clients / libs using factomd API.

So I suggest to improve `diagnostics` API call and expand it with following params:
`"inignore":true/false`

@ThomasMeier, Brian suggested to ask you to explore this.

**Comment by carryforward** [comment]
yeah, the diagnostics API is now in the master branch.  It is easing its way into production as we gain more confidence, but all the things we are building on now are assuming they are derived or mergeable into the latest master.

After looking at the code, I think the thing that Anton might be looking for is the sync info.  That tells if the node thinks it is following by minutes.  This will tell anything using the node if it is still booting and downloading the 1st and 2nd pass.
https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/wsapi/wsapiV2.go#L1431 

There might be a use for knowing when a node has finished loading from disk though, which is largely what ignore mode is.

lets explore what ignore mode is.  It might not exist in the mid term future, as it was kind of a band aid that has since been solved differently.  

In the past, when booting multiple machines, they would go through the wait period (as federated servers) then would go through the ignore period.  While in ignore mode, the missing-message code is disabled.  Lets explore this.

Since the p2p network can and does drop messages when they are flooding around the network, when a server adds a new item to the process list, it is given an index in that process list.  The problem was that when the network was rebooted, the different nodes couldn't tell if a particular acknowledgement (the thing that puts an item at a particular place in the process list) is part of the current runtime, or if it had been floating around the network from the past, before the reboot.  The ignore period was an attempt to get the nodes to not ask peers for missing messages during that time, making the assumption that new messages that came were part of the current boot.

During the Sep 27, 2018 stall this was shown to be ineffective.  A new methodology of self protection from the past during reboots was developed then.  Nodes ignore any messages that have a timestamp from before the node was booted.  (This is why you will see a lot of nils in your process list when you boot it at first that don't get filled in.  The follower you boot must fall back to following by blocks instead of using the process list for the first block when it is booted for this reason.)

The second thing that ignore mode does is that it prevents factomd from asking for things over the network while it still probably has it in the database, and it is just taking a little while to works its way from the disk, through the queues, into where the consensus code is waiting. It probably won't go away soon for that reason, and will be needed in some capacity.

Knowing we have caught up with the latest block is a fairly hard problem.  There are a few strategies we are thinking of, but it isn't going to be something achievable in the near term.  It would be nice if we were able to know that too.  It got harder with the latest release, since we effectively no longer report the leaderheight in the heights API call, since we can't rely on the data source we were deriving the info from.

All that being said, I think the important info that Anton is asking for is to know if a factomd node has fully booted.  Right now we are using ignore mode as a proxy for determining if a node has finished booting.  I suspect the metric that we use to determine fully booted will change over time.  Just looking at the ignore mode probably isn't going to be effective long term.  Instead lets report back over the API if the node thinks it is fully booted.  The things that feed into that will change over time.  Also there are already different definitions of what a fully booted node is.  

If the first pass is completed, and a node is following by blocks, but is still behind on the 2nd pass, so can't follow by minutes, is that fully booted?  I suppose ignore mode is telling you that the node has fully booted from disk.  It may not be up to date on the network, but the local node can know if it has loaded everything from disk.

Lets call this thing we are talking about as knowing we are done booting from disk.  It would only look at the first pass (dbstates) and the second pass would be reported elsewhere.  (there are more plans for the second pass, as it won't need to download all the entries eventually.)  The API already report back if it is following by minutes here: https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/wsapi/wsapiV2.go#L1431

Lets add a new thing for the diagnostics API to return if the node is done booting from disk.  There is a flag on the last block saved to the database that sets a flag in the state somewhere that no more dbstates are coming from the disk.  Ignore mode is really just a timer that starts after that last database block is loaded.  Since we already have a way of knowing if we are following with minutes, we should instead concentrate on knowing when we are booted.  The end of the ignore mode isn't really important.  it is just a period where we know it won't try catching up with the blockchain.  There isn't much difference between not trying to catch up, and trying, but being in progress.

Lets have a new item in the diagnostics API called `bootfromdiskdone`.  It can report back based on if there are more dbstates being loaded from the database.  (I apologize I don't remember the flag indicating it.  it shouldn't be too hard to find though)

https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/wsapi/wsapiStructs.go#L307
https://github.com/FactomProject/factomd/blob/5f787fc9bf067dac6df2c36803e03e2a1a3b3186/wsapi/wsapiV2.go#L180
https://github.com/FactomProject/factomd/blob/master/wsapi/wsapiV2.go#L1391

**Comment by carryforward** [comment]
here is a branch to make pull requests against: https://github.com/FactomProject/factomd/tree/FD-869_fully_booted_diagnostics_API

**Comment by carryforward** [comment]
is this something you think you can handle @ThomasMeier ?

**Comment by ThomasMeier** [comment]
Yes, trying this approach now. I put one together on friday based on `IgnoreDone` but set it aside for this approach. It sounds like it'll be useful beyond when/if ignore mode is discontinued.

**Comment by ilzheev** [comment]
```
There might be a use for knowing when a node has finished loading from disk though, which is largely what ignore mode is.
```
I agree with @carryforward that `bootfromdiskdone` is better to use than just `outofignore`.

When node is out of ignore, the entries from entryblocks may still being fetched.

So, it’s even better to have a marker not for ignore mode, but for loading from disk finished. 
And node:
1) May process create chains, entries, tx requests correctly
2) Returns 100% actual information for read requests

---

From the Open API monitoring side, I wanted to implement 2 conditions, that should be simultaneously met, to include node into pool after restart:
1) Node is out of ignore
2) Node's EntryHeight >= (LeaderHeight-1)

But, having `bootfromdiskdone` call makes this check easier and allows to rely only on this API call.

So, it's definitely better to implement `bootfromdiskdone`, on my mind.

**Comment by carryforward** [comment]
I think the flag that this API call would be based on is just for the first pass.  I'm not sure if it also shows as being false if the the second pass is not done.  @ThomasMeier would this one show as being done loading from disk if the second pass is still behind?

**Comment by carryforward** [comment]
@ilzheev for the most effectiveness, you probably want to instead use the metric that the node is following by minutes rather than just looking at local conditions, like that it had finished booting.  The two conditions you have mentioned are indicators that it is close to following along with consensus, but to see those directly you probably want to just measure it directly.  `syncing` is what you are looking for.

https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/wsapi/wsapiStructs.go#L321

**Comment by jcheroske** [comment]
I appreciate all the good work going on here. I do want to mention that knowing about conditions such as, "is the node done booting from the disk?" really feels like a leaky abstraction. As an API user, why do I care about that? I want to know if the API is open for business. Can you tell me that? I've spent way too much time trying glean the state of factomd by looking at various vague indicators, and, at this point, have no confidence in anything I've done. `heights`, `current-minute`, and now `diagnostics`, and none of them clearly answer the question, or the information they used to convey is changing with a new release. Please tell me if the API is ready, and do it in a way that a noob will understand. 

Right now, I make four!!! API calls to gather up all the information I'd like to include in the health check payload. A `status` method that included the following would be nice:

```js
{
  version: '6.2.1-rc2',
  currentTime: 1552373681,
  leaderHeight: 17204, // this is going away?
  directoryBlockHeight: 17204,
  entryHeight: 17204,
  entryBlockHeight: 17204, // is this even a thing anymore?
  minute: 5, // 0-9, null when not following minutes
  currentBlockStartTime: 1552373675, // null when not synced
  currentMinuteStartTime: 1552373675, // null when not following minutes
  isSynced: true,
  isFollowingMinutes: false,
  isApiReady: false,
}
```
The great thing about something like `isApiReady`, is it's name is not tied to any underlying implementation. Factomd is free to change and evolve however it does, and as long as you answer that question you've maintained the contract.

**Comment by ThomasMeier** [comment]
@carryforward the`bootfromdiskdone` will show true even when second pass hasn't yet completed.

**Comment by ilzheev** [comment]
Having a `bootfromdiskdone` flag, that detects that first pass has completed, is also useful.
What's about adding additional flag `apiready`?

```
if BootFromDiskDone == true && EntryHeight+1 >= LeaderHeight {
APIReady := true
} else {
APIReady := false
}
```

**Comment by ilzheev** [comment]
I've just tested on my testnet node (6.2.1-rc2).
When dblocks fetched from disk completely, the LeaderHeight is updated from the network.
So the combination of 2 conditions above to define `APIReady` should work without false alarms.
@carryforward @ThomasMeier what do you think about it?

**Comment by carryforward** [comment]
oof, this is why I am generally resistant to adding new APIs without careful consideration.  It is looking like the initial FD-869 call is turning out to not actually solve the problem that is happening.  While this is a useful call, and will certainly be useful in the future, it didn't actually solve the problem the OpenNode team has.  This is a bit disappointing, but reaffirms the policy of moving very slowly when deciding to add new APIs.

I don't like adding new APIs because it is not just the cost of the initial coding + code review + testing + merging/tracking + documentation follow up + version management.  That is all knowable in the short term.  The bigger cost is the maintenance and continual testing and verification going into the future, indefinitely.  This cost is borne by QA, which is hard to quantify.  Maintaining quality is hard.

This FD-869 call was introduced without a unit test.  Normally we like to add a unit test to new bits of code that get added to factomd.  It was a bit hard to make a unit test for this, since it relies on the state being in a particular configuration.  This will likely be part of a different test process going forward. Please don't expect this low attention to quality (lack of unit tests) to be the norm.  

Now, this is the diagnostic API, so there is a lot less assurance than @jcheroske is likely expecting from especially this API (i.e. there should be far less expectation of any so called "contract").  Since so many of the items are tagged as `omitempty` they should not be relied upon being there 
https://github.com/FactomProject/factomd/blob/56572d60255eaa3e54991182addb10f9c0a53985/wsapi/wsapiStructs.go#L329

Sadly bool's are far more difficult to leave as returning nothing when they are meaningless, so in the current code they are always returned.  The problem is that these rely on the big unified State object.  This is one of the big things that we are trying to eliminate as the code transforms through the refactoring over the next few years.

Lets move the discussion about how to move forward from here to a new thread. https://github.com/FactomProject/factomd/issues/671
